- name: Install pycurl for apt_repository
  apt: pkg=python-pycurl state=present

- name: Add postgres repository
  apt_repository: repo='deb http://apt.postgresql.org/pub/repos/apt/ precise-pgdg main' state=present

- name: Add postgres repository key
  apt_key: url=http://apt.postgresql.org/pub/repos/apt/ACCC4CF8.asc state=present

- name: Install postgresql
  apt: pkg=postgresql-9.3 state=present force=yes

- name: Apply pg_hba config
  template: src=pg_hba.conf dest=/etc/postgresql/9.3/main/pg_hba.conf owner=postgres group=postgres
  notify: restart postgresql

- name: Install postgresql-ansible requirements
  action: apt name={{ item }} state=installed update-cache=yes
  with_items:
    - libpq-dev
    - python-dev
    - python-pip

- name: Install pip package for postgresql
  pip: name=psycopg2

- name: Create brainwashing database
  postgresql_db: name=bw_production
  sudo: yes
  sudo_user: postgres

- name: Create brainwashing database user
  postgresql_user: db=bw_production name=bw password=ceec4eif7ya
  sudo: yes
  sudo_user: postgres
