- name: Ruby | Installs ruby building dependencies
  action: apt name={{ item }} state=installed update-cache=yes
  with_items: ruby_deps
  tags:
    - ruby
    - ruby:install
    - install

- name: Ruby | Ensure that ruby_deploy_user exists
  user: name={{ ruby_deploy_user }} state=present groups=sudo
