- name: See if target ruby is installed
  stat: path=~/.rbenv/versions/{{ version }}
  register: ruby_is_installed
  tags:
    - ruby
    - ruby:install
    - install

- name: Ruby | Installs ruby
  action: shell cd; bash -lc "rbenv install {{ version }}"
  when: ruby_is_installed.stat.exists == false

  # Takes no more than 600 secs on a small VM
  # time limit to compile ruby
  async: 1200
  poll: 30
  tags:
    - ruby
    - ruby:install
    - install
